# Ansible inventory config
dn42routers:
  children:
    na:
      hosts:
        yvr:
          smokeping_id: yvr01
          server_isp: BandwagonHost
          ansible_host: yvr.peer.highdef.network
          public_host_v6: 6.yvr.peer.highdef.network
          ownip: 172.22.108.35
          ownip6: fd86:bad:11b7:35::1
          region: NANorthwest
          # 44 = North America - West
          dn42_regions: [44]
          location: "Vancouver, BC, CA"
          location_alt:
          - Seattle, WA, US
          wg_pubkey: "O4qWRgbJVdOM8ktyUQyT1s11WkR16JTgtnn42m9A2R8="
          link_local_ip6: "fe80::1080:35"
          link_local_ip4: "169.254.108.35"
          igp_neighbours_append:
          - name: igp-yvrlab
            cost: "10"
          igp_upstreams:
          - sjc
          - ymq
          notes:
          - IPv6 is tunneled through Seattle (<b>6.yvr.peer.highdef.network</b>) - please prefer IPv4, or use MTU 1400 for WireGuard tunnels over IPv6.

        sjc:
          smokeping_id: sjcpeer
          server_isp: GreenCloudVPS
          ansible_host: sjc.peer.highdef.network
          ownip: 172.22.108.34
          ownip6: fd86:bad:11b7:34::1
          region: NAWest
          # 44 = North America - West
          dn42_regions: [44]
          location: "San Jose, CA, US"
          location_alt:
          - Los Angeles, CA, US
          - Las Vegas, NV, US
          wg_pubkey: "Kz7mZN2ACCXSFKMiZDIVdVRmEPSnVfbEOqsxsDZ6hAw="
          link_local_ip6: "fe80::1080:34"
          link_local_ip4: "169.254.108.34"
          igp_upstreams:
          - ymq
          - ams
          igp_neighbours_append:
          - name: igp-yvrlab
            cost: "30"

        chi:
          smokeping_id: chi02a
          server_isp: GreenCloudVPS
          ansible_host: chi02.jlu5.com
          public_host: chi.peer.highdef.network
          ownip: 172.20.229.113
          ownip6: fd86:bad:11b7:13::1
          region: NACentral
          dn42_regions: [43]
          location: "Chicago, IL, US"
          wg_pubkey: "u4WJMAoCHIOeh/+6NWMytNygp+/wrMogB+rwyVzXoEg="
          link_local_ip6: "fe80::113"
          link_local_ip4: "169.254.108.113"
          igp_upstreams:
          - sjc
          - ymq
          igp_neighbours_append:
          - name: igp-yvrlab
            cost: "55"

        ymq:
          smokeping_id: ovh-bhs
          server_isp: OVH
          ansible_host: ymq.peer.highdef.network
          ansible_port: 222
          ownip: 172.20.229.123
          ownip6: fd86:bad:11b7:23::1
          region: NAEast
          # 42 = North America - East
          dn42_regions: [42]
          location: "Montreal, QC, CA"
          wg_pubkey: "YrlNsVP9bbTqNuNyQ/MVFzulZKNW5vMaDMzHVFNXSSE="
          link_local_ip6: "fe80::123"
          link_local_ip4: "169.254.108.123"
          stub_ifnames_append: [eth0]
          igp_upstreams:
          - sjc
          - chi
          - yvr
          - ams
          igp_neighbours_append:
          - name: igp-yvrlab
            cost: "75"
          location_alt:
          - Toronto, ON, CA
          - New York City, NY, US
          static_routes4:
          - 172.22.108.80/31 via 172.22.108.50

        dal:
          smokeping_id: dal03
          server_isp: CometVPS
          ansible_host: dal.peer.highdef.network
          ownip: 172.22.108.33
          ownip6: fd86:bad:11b7:33::1
          region: NACentral
          # 43 = North America - Central
          dn42_regions: [43]
          location: "Dallas, TX, US"
          wg_pubkey: "gTSNP0p+Ok3gaw0mcB1yhuZ2obaoOUxW+jPI2KxGAkc="
          link_local_ip6: "fe80::1080:33"
          link_local_ip4: "169.254.108.33"
          igp_upstreams:
          - chi
          - sjc
          - ymq
          - yvr
          - lon

        ash:
          smokeping_id: ash02
          server_isp: GreenCloudVPS
          ansible_host: ash.peer.highdef.network
          ownip: 172.20.229.112
          ownip6: fd86:bad:11b7:12::1
          # 42 = North America - East
          dn42_regions: [42]
          region: NAEast
          location: "Ashburn, VA, US"
          wg_pubkey: "6g9a5XuPZhKvhQrxeogmfBlP1YkO/DBRA9niMg7RADY="
          link_local_ip6: "fe80::1080:112"
          link_local_ip4: "169.254.108.112"
          igp_upstreams:
          - chi
          - dal
          - ymq
          - sjc
          - yvr

        atl:
          smokeping_id: atl02
          server_isp: SmartHost
          ansible_host: atl.peer.highdef.network
          ownip: 172.20.229.119
          ownip6: fd86:bad:11b7:9::1
          # 42 = North America - East
          dn42_regions: [42]
          region: NAEast
          location: "Atlanta, GA, US"
          wg_pubkey: "gbhhdvAIHVuv5e+tIG/m9T9fDaGoAGVgSUHq+rKTLyY="
          link_local_ip6: "fe80::1080:119"
          link_local_ip4: "169.254.108.119"
          igp_upstreams:
          - ash
          - chi
          - dal
          - ymq
          - sjc
          - yvr

    eu:
      hosts:
        lon:
          smokeping_id: lon02a
          server_isp: Clouvider
          public_host: lon.peer.highdef.network
          ansible_host: 2a0a:8dc0:188:4242::2
          ownip: 172.20.229.116
          ownip6: fd86:bad:11b7:116::1
          region: EU
          # 41 = Europe
          dn42_regions: [41]
          location: "London, UK"
          wg_pubkey: "pEQZQOD67QeWXqrHLrMoCXug/cOXJFMXH5vwQ1cW70s="
          link_local_ip6: "fe80::116"
          link_local_ip4: "169.254.108.116"
          igp_upstreams:
          - ams
          - ymq
          - chi
          - ash
          - atl
          stub_ifnames_append: [eth0]

        ams:
          smokeping_id: ams04
          server_isp: UltraVPS
          ansible_host: ams.peer.highdef.network
          ownip: 172.20.229.117
          ownip6: fd86:bad:11b7:117::1
          region: EU
          # 41 = Europe
          dn42_regions: [41]
          location: "Amsterdam, NL"
          location_alt:
          - Frankfurt, DE
          - Nuremberg, DE
          wg_pubkey: "oiSSSOMYxiiM0eQP9p8klwEfNn34hkNNv4S289WUciU="
          link_local_ip6: "fe80::117"
          link_local_ip4: "169.254.108.117"
          igp_upstreams:
          - sjc
          - ymq
          - chi

        sto:
          smokeping_id: sto01
          server_isp: HostHatch
          ansible_host: sto.peer.highdef.network
          ownip: 172.20.229.121
          ownip6: fd86:bad:11b7:121::1
          region: EU2
          # 41 = Europe
          dn42_regions: [41]
          location: "Stockholm, SE"
          wg_pubkey: "S82d2xkBdKzdx0i0vrS/sjScAjOHbUqZ0kDGf6drYAo="
          link_local_ip6: "fe80::1080:121"
          link_local_ip4: "169.254.108.121"
          igp_upstreams:
          - ams
          - lon
          - ash

    apac:
      hosts:
        tyo:
          smokeping_id: tyo04
          server_isp: GreenCloudVPS
          ansible_host: tyo.peer.highdef.network
          ownip: 172.20.229.124
          ownip6: fd86:bad:11b7:224::1
          region: AsiaEast
          # 52 = Asia-E (JP,CN,KR)
          dn42_regions: [52]
          location: "Tokyo, JP"
          wg_pubkey: "iJXjwJGGrUTQy/P3OXmZ5lM4cjrDAd9K+vonZVUZjxY="
          link_local_ip6: "fe80::124"
          link_local_ip4: "169.254.108.124"
          igp_upstreams:
          - sjc
          - yvr
          - ams
          stub_ifnames_append: [lxcbr0]

        hkg:
          smokeping_id: hkg02
          server_isp: GreenCloudVPS
          ansible_host: hkg.peer.highdef.network
          ownip: 172.22.108.38
          ownip6: fd86:bad:11b7:238::1
          region: AsiaEast
          # 52 = Asia East
          dn42_regions: [52]
          location: "Hong Kong, HK"
          wg_pubkey: "eedTHubyl5caiHH50GkknQa8SQtAF8q7aqmL26w5qSs="
          link_local_ip6: "fe80::1080:38"
          link_local_ip4: "169.254.108.38"
          igp_upstreams:
          - tyo
          - syd
          - sjc
          - yvr

        sgp:
          smokeping_id: sgp02
          server_isp: GreenCloudVPS
          ansible_host: sgp.peer.highdef.network
          ownip: 172.22.108.39
          ownip6: fd86:bad:11b7:239::1
          # 51 = Asia Southeast
          dn42_regions: [51]
          location: "Singapore, SG"
          region: AsiaSouthCentral
          wg_pubkey: "X3m9VMzZYN4Oe2QUb7DcnmVymwKSLbPUCB5ElD8igjo="
          link_local_ip6: "fe80::1080:39"
          link_local_ip4: "169.254.108.39"
          igp_upstreams:
          - tyo
          - hkg
          - sjc
          - ams

        syd:
          smokeping_id: syd01
          server_isp: HostHatch
          ansible_host: syd.peer.highdef.network
          ownip: 172.20.229.125
          ownip6: fd86:bad:11b7:225::1
          region: Oceania
          # 53 = Pacific
          dn42_regions: [53]
          location: "Sydney, AU"
          wg_pubkey: "Xk9wCuwp3zK4WflTeAKBIjgIlr3+qUwIFCkF2uMyyF8="
          link_local_ip6: "fe80::1080:125"
          link_local_ip4: "169.254.108.125"
          igp_upstreams:
          - sjc
          - tyo
          - sgp
          - ams

        mum:
          smokeping_id: mum01
          server_isp: HostDZire
          ansible_host: mum.peer.highdef.network
          ansible_port: 222
          ownip: 172.20.229.120
          ownip6: fd86:bad:11b7:220::1
          region: AsiaSouthCentral
          # 50 = Asia South
          dn42_regions: [50]
          location: "Mumbai, IN"
          wg_pubkey: "PrYhKlV2860pNQOWgn8dO6kkvl0SZIZ7cZbWSq8wuV4="
          link_local_ip6: "fe80::1080:120"
          link_local_ip4: "169.254.108.120"
          v4_only: true
          igp_upstreams:
          - lon
          - ams
          - tyo
          - hkg
          - sgp
          - syd
          static_routes4:
          - 172.22.108.60/30 via 172.22.108.60

    sa:
      hosts: {}

anycast_recursors:
  hosts:
    yvr:
    sjc:
    chi:
    dal:
    ash:
    atl:
    ymq:
    lon:
    ams:
    sto:
    tyo:
    hkg:
    sgp:
    syd:
    mum:

# This should be a subset of anycast_recursors
anycast_auth_dns:
  hosts:
    sjc:
    chi:
    ymq:
    ams:
    tyo:

# Clearnet web hosts, serving Bird-lg-go and splash site publicly
# Only one server at a time, since this is using HTTP verification to retrieve certs
web:
  hosts:
    ams:
routegraphs:
  hosts:
    ams:

# Misc hosts managed by Ansible - not open to peering
private:
  hosts:
    ymq2:
      ansible_host: 2602:ffd5:1:2af::3
      ownip: 172.22.108.43
      ownip6: fd86:bad:11b7:f11e::3
      region: NAEast
      dn42_regions: [42]
      location: "Montreal, QC, CA"
      wg_pubkey: "Zh1VbPf4TULZDxyzT0D/tz0Hc8u1CS35owMPYJewIW8="
      link_local_ip6: "fe80::1080:43"
      link_local_ip4: "169.254.108.43"
      igp_upstreams:
      - ymq
      - chi
      - sjc
      - ams
      ibgp_rr_upstreams: []
      stub_ifnames_append: [eth0]
      igpping_override:
        ymq3: 1

    ymq3:
      ansible_host: ymq03.jlu5.com
      ownip: 172.22.108.32
      ownip6: fd86:bad:11b7:a332::1
      region: NAEast
      dn42_regions: [42]
      location: "Montreal, QC, CA"
      wg_pubkey: "r+uca6ieMJ3VHWohNwOhRx+TXhydzWx2+4ObQrCBG3M="
      link_local_ip6: "fe80::1080:32"
      link_local_ip4: "169.254.108.32"
      igp_upstreams:
      - ymq
      - ymq2
      - yvr
      ibgp_rr_upstreams: []
      smokeping_base_url: "ping-ymq3.highdef.dn42"
      smokeping_id: ymq03
      igpping_override:
        ymq2: 1

    tyo2:
      ansible_host: tyo07.jlu5.com
      ownip: 172.22.108.36
      ownip6: fd86:bad:11b7:236::1
      region: AsiaEast
      dn42_regions: [52]
      location: "Tokyo, JP"
      wg_pubkey: "HeQ8MyuwiizpKz46Ipf+8Or6xteh76C0ynm6POYYrgI="
      link_local_ip6: "fe80::1080:36"
      link_local_ip4: "169.254.108.36"
      igp_upstreams:
      - sjc
      - yvr
      - tyo
      - hkg
      - syd
      ibgp_rr_upstreams: []
      smokeping_base_url: "ping-tyo2.highdef.dn42"
      smokeping_id: tyo07

    lax:
      ansible_host: lax03.jlu5.com
      ownip: 172.22.108.48
      ownip6: fd86:bad:11b7:48::1
      # 44 = North America - West
      dn42_region: 44
      region: NAWest
      location: "Los Angeles, CA, US"
      wg_pubkey: "FNYqGNN77foNRBsXRzrqV/CBD5E1fcWaac+kbl0jPik="
      link_local_ip6: "fe80::1080:48"  # fe80::122
      link_local_ip4: "169.254.108.48"
      dn42_regions: [44]
      ibgp_rr_upstreams: []
      smokeping_base_url: "ping-lax.highdef.dn42"
      smokeping_id: lax03
      igp_upstreams:
      - chi
      - sjc
      - dal
      - yvr

  children:
    ixprouters:
      hosts: {}

smokeping:
  hosts:
    yvrping:
      ansible_host: 172.22.108.3
      ownip: 172.22.108.3
      ownip6: fd86:bad:11b7:aaaa:38c2:3ff:fe0b:5860
      smokeping_base_url: "ping.highdef.dn42"
      location: "Vancouver, BC, CA"
      smokeping_dn42: true
      region: NANorthwest
      smokeping_target_regions:
        full: [NAEast]
        lite: [NAWest, NACentral, NASoutheast, EU, AsiaEast]
    yvr:
    ymq:
    ymq3:
    sjc:
    lax:
    chi:
    dal:
    ash:
    atl:
    lon:
    ams:
    sto:
    tyo:
    tyo2:
    hkg:
    sgp:
    syd:
    mum:
