- name: Setup extensions for dn42 routers
  hosts: dn42routers
  become: yes
  roles:
    # These are optional roles only needed for nodes open to peering
    # This should run after reconfigure.yml as the dn42 dummy interfaces need to be created first.
    - setup-bird-lg-go
    - setup-extra-scripts
    - setup-routestats

- name: Setup webtrace
  hosts: webtrace
  become: yes
  roles:
    - setup-webtrace
