- name: "Remove obsolete WireGuard tunnel configs"
  file:
    dest: "/etc/wireguard/{{ peer_name }}.conf"
    state: absent
  loop: "{{ peers_to_remove }}"
  loop_control:
    loop_var: peer_name
  register: wg_conf_remove

- name: "Remove obsolete interface configurations"
  shell:
    cmd: "rm -fv {{ automation_root_dir | quote }}/interfaces/??{{ peer_name | quote }}"
  loop: "{{ peers_to_remove }}"
  loop_control:
    loop_var: peer_name
  register: interfaces_remove
  changed_when: interfaces_remove.stdout != ""

- name: "Stop obsolete interfaces"
  command: "ip link del {{ peer_name }}"
  loop: "{{ (wg_conf_remove.results + interfaces_remove.results)
            | selectattr('changed', 'true') | map(attribute='peer_name') | unique }}"
  loop_control:
    loop_var: peer_name
  ignore_errors: yes
