#!/usr/bin/env python3
"""
Generate DNS config:
- forward-zones and DNSSEC config for pdns-recursor
- secondary zones list for pdns
"""

import argparse
import collections
import dataclasses
import itertools
import ipaddress
import logging
import os.path
import pathlib

import yaml

from _common import AUTOGENERATED_COMMENT
from _netutils import get_ptr_zone

_CLEARNET_DNS_SERVERS=['1.1.1.1', '1.0.0.1', '8.8.8.8', '8.8.4.4']
_SYSTEM_ROOT_DS = '/usr/share/dns/root.ds'

@dataclasses.dataclass
class RegistryDNSEntry:
    path: pathlib.Path
    zone: str
    nameserver_ips: list[str]
    trust_anchors: list[str]
    uses_delegation_server: bool = False

    def is_forward_zone(self):
        if self.zone.endswith('.dn42'):
            return False
        if self.zone.endswith('.arpa'):
            return self.uses_delegation_server
        return True

class ForwardZonesGenerator():
    def __init__(self, registry_path: str):
        self.registry_path = pathlib.Path(registry_path)

        self._delegation_server_ips = collections.defaultdict(set)

        # Populate _seen_nameservers with delegation-servers IPs
        dn42_delegation_servers = self._read_registry_dns_file(
            self.registry_path / 'data' / 'dns' / 'delegation-servers.dn42')
        assert dn42_delegation_servers
        assert dn42_delegation_servers.nameserver_ips

        self.recursor_conf = {}
        self._all_zones: dict[str, RegistryDNSEntry] = {}

    @staticmethod
    def _read_system_ds() -> list[str]:
        """Return a list of DS records for the root zone (.)"""
        result = []
        prefix = '. IN DS '
        with open(_SYSTEM_ROOT_DS, encoding='utf8') as f:
            for line in f.readlines():
                line = line.strip()
                assert line.startswith(prefix), f'Invalid DS string {line}'
                result.append(line[len(prefix):])
        return result

    @staticmethod
    def _read_registry_line(line, prefix: str) -> str:
        prefix = prefix.removesuffix(':') + ':'
        if line.startswith(prefix):
            return line.removeprefix(prefix).strip()
        return ""

    def _read_registry_dns_file(self, path: pathlib.Path) -> RegistryDNSEntry | None:
        """
        Return a list of nameservers and DS records (when available) from a dn42 registry DNS entry
        """
        result = RegistryDNSEntry(path, "", [], [])
        filename = path.name

        with open(path, encoding='utf-8') as f:
            for line in f.readlines():
                if domain := self._read_registry_line(line, 'domain'):  # data/dns
                    result.zone = domain
                elif cidr := self._read_registry_line(line, 'cidr'):  # data/inetnum, data/inet6num
                    try:
                        result.zone = get_ptr_zone(cidr)
                    except ValueError:
                        logging.debug("No valid PTR zone for CIDR %s", cidr)
                        return None
                elif nserver_data := self._read_registry_line(line, 'nserver'):
                    if ' ' in nserver_data:  # nserver:    foo.bar.baz 1.2.3.4
                        nserver_name, nserver_ip = nserver_data.split(None, 1)
                        try:
                            ipaddress.ip_address(nserver_ip)
                        except ValueError:
                            logging.warning('[%s] Could not parse nserver %r as IP, ignoring', filename, nserver_ip)
                            continue
                        if result.zone == 'delegation-servers.dn42':
                            self._delegation_server_ips[nserver_name].add(nserver_ip)
                    else: # nserver:    just.a.name
                        nserver_name = nserver_data
                        nserver_ip = None
                    if nserver_name.endswith('.ipv4.registry-sync.dn42'):
                        # 4.3.2.1.ipv4.registry-sync.dn42 -> 1.2.3.4
                        nserver_ip = '.'.join(nserver_name.split('.')[3::-1])
                    elif nserver_name.endswith('.ipv6.registry-sync.dn42'):
                        nserver_chars = nserver_name.split('.')[-4::-1]
                        nserver_chunks = [''.join(nserver_chars[i:i+4]) for i in range(0, len(nserver_chars), 4)]
                        nserver_ip = ':'.join(nserver_chunks)
                    elif nserver_name.endswith('.delegation-servers.dn42'):
                        result.uses_delegation_server = True
                        nserver_ips = self._delegation_server_ips[nserver_name]
                        assert nserver_ips, f"Could not find IPs for {nserver_name}"
                        result.nameserver_ips += sorted(nserver_ips)
                        logging.debug('[%s] Expanding delegation server %s -> %s', filename, nserver_name, nserver_ips)
                        continue
                    elif nserver_name.endswith('.dn42'):  # not our zone
                        continue

                    if nserver_ip:
                        result.nameserver_ips.append(nserver_ip)
                    else:
                        logging.warning('[%s] Could not parse nserver %r', filename, nserver_data)
                if line.startswith('ds-rdata'):
                    ta = line.split(None, 1)[-1].strip()
                    result.trust_anchors.append(ta)
        assert result.zone
        return result

    def populate_zone(self, path: pathlib.Path):
        """Try to populate a forward or reverse DNS zone"""
        entry = self._read_registry_dns_file(path)
        if not entry:
            return

        zone = entry.zone
        if old_entry := self._all_zones.get(zone):
            raise RuntimeError(f"Duplicate zone {zone!r} ({old_entry.path} -> {entry.path})")
        self._all_zones[zone] = entry

        if not entry.is_forward_zone():
            return
        if entry.nameserver_ips:
            self.recursor_conf['recursor']['forward_zones'].append({
                'zone': zone,
                'forwarders': entry.nameserver_ips
            })
            logging.info('[%s] forwarders=%s', zone, entry.nameserver_ips)
        else:
            logging.warning('[%s] No valid forwarders found, skipping', zone)
            return

        if entry.trust_anchors:
            self.recursor_conf['dnssec']['trustanchors'].append({
                'name': zone,
                'dsrecords': entry.trust_anchors
            })
            logging.info('[%s] trustanchors=%s', zone, entry.trust_anchors)
        else:
            self.recursor_conf['dnssec']['negative_trustanchors'].append({
                'name': zone,
                'reason': 'no trust anchors found in dn42 registry'
            })
            logging.info('[%s] no trust anchors found', zone)

    def generate(self):
        self.recursor_conf = {
            'recursor': {
                'forward_zones_recurse': [
                    {
                        'zone': '.',
                        'forwarders': _CLEARNET_DNS_SERVERS
                    }
                ],
                'forward_zones': []
            },
            'dnssec': {
                'trustanchors': [
                    # Ideally we can import this from the system DS file directly, but
                    # https://github.com/PowerDNS/pdns/issues/14999 prevents this from working properly
                    {
                        'name': '.',
                        'dsrecords': self._read_system_ds()
                    }
                ],
                'negative_trustanchors': []
            }
        }

        # Fill in dn42 zones
        dn42_zones = itertools.chain(
            self.registry_path.glob('data/dns/*'),
            self.registry_path.glob('data/inetnum/*'),
            self.registry_path.glob('data/inet6num/*'),
        )
        for dns_entry_path in dn42_zones:
            self.populate_zone(dns_entry_path)

    def write_recursor_config(self, filename):
        with open(filename, 'w', encoding='utf8') as f:
            f.write(f"# {AUTOGENERATED_COMMENT}\n")
            yaml.dump(self.recursor_conf, f, sort_keys=False)

    def write_secondary_zones_list(self, filename):
        secondary_zones = [
            zone for zone, entry in self._all_zones.items()
            if entry.uses_delegation_server
        ]
        with open(filename, 'w', encoding='utf8') as f:
            f.write(f"# {AUTOGENERATED_COMMENT}\n")
            yaml.dump({
                "dns_dn42_secondary_zones": secondary_zones,
            }, f, sort_keys=False)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '-v', '--verbose',
        action='count',
        default=0,
        help="enable verbose logging (-v for INFO, -vv for DEBUG)"
    )
    parser.add_argument("registry_path", help="path to dn42 registry Git repo", type=pathlib.Path)
    args = parser.parse_args()

    if args.verbose == 0:
        log_level = logging.WARNING
    elif args.verbose == 1:
        log_level = logging.INFO
    else:
        log_level = logging.DEBUG
    logging.basicConfig(level=log_level)

    rootdir = pathlib.Path(os.path.dirname(__file__)) / ".."
    os.chdir(rootdir)
    g = ForwardZonesGenerator(args.registry_path)
    g.generate()
    g.write_recursor_config(rootdir / 'global-config' / 'pdns-recursor' / 'dn42-zones.yml')
    g.write_secondary_zones_list(rootdir / 'global-config' / 'dns-zones-secondary.yml')

if __name__ == '__main__':
    main()
