gre_peers:
- name: dn42-ldti
  remote: "212.150.193.88"
  peer_v4: 169.254.123.2
  local_v6: fd86:bad:11b7:7f42:3772::0/127
  bgp:
    asn: 4242423772
    extended_next_hop: false
    ipv4: true
    ipv6: true
    mp_bgp: true
